CREATE TABLE Facultad (
Codigo INT,
Nombre NVARCHAR (100),
PRIMARY KEY (Codigo)
);

CREATE TABLE Investigadores (
DNI VARCHAR(8),
NomApels NVARCHAR (255),
Facultad INT,
PRIMARY KEY (DNI),
FOREIGN KEY (Facultad) REFERENCES Facultad(Codigo)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Equipos (
NumSerie CHAR(4),
Nombre NVARCHAR (100),
Facultad INT,
PRIMARY KEY (NumSerie),
FOREIGN KEY (Facultad) REFERENCES Facultad(Codigo)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Reserva (
DNI VARCHAR(8),
NumSerie CHAR(4),
Comienzo DATETIME,
Fin DATETIME,
PRIMARY KEY (DNI,NumSerie),
FOREIGN KEY (DNI) REFERENCES Investigadores(DNI),
FOREIGN KEY (NumSerie) REFERENCES Equipos(NumSerie)
ON DELETE CASCADE ON UPDATE CASCADE
);

